### ISSUE TITLE
Create block for Vimeo video player

### ISSUE THREAD

**Issue by pardeepgera23** [hlxsites/aldevron#100]
**Summary:**

Create a block for playing video using Vimeo links.
Example from existing website: https://www.aldevron.com/25th-anniversary

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
Added a bug.

Vimeo video player- Div width and height and fast forward 5secs issue #159

**Comment by Kummu007** [comment]
This is working as expected.
