### ISSUE TITLE
Article cards- Tooltip Text Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#102]
Hi Team,

I have noticed that when the mouse moves over the CTA the tooltip text appears on the screen. Please look into the below snap and do the needful.

![image](https://github.com/hlxsites/aldevron/assets/117751754/09fe1a03-1c9a-4caf-b3cb-514366a6039f)
![image](https://github.com/hlxsites/aldevron/assets/117751754/ebf6eb28-ad56-4bb4-9198-22e46bc469ab)
![image](https://github.com/hlxsites/aldevron/assets/117751754/91950489-f34a-48c1-bccc-6beb4d033135)

**Comment by gowtamibetireddy** [comment]
https://main--aldevron--hlxsites.hlx.page/qe-test/articalcards
https://feature-ac-bug-102--aldevron--hlxsites.hlx.page/qe-test/articalcards
https://feature-ac-bug-102--aldevron--hlxsites.hlx.page/test/campus

**Comment by gowtamibetireddy** [comment]
@Kummu007 this issue has been fixed & its ready for QA

**Comment by Kummu007** [comment]
Hi @gowtamibetireddy thanks for the update, this is working as expected. Hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/91ea3563-36bd-4295-9ec0-5fe740fa2917)
