### ISSUE TITLE
Article cards- Mobile View Image Resize Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#103]
Hi Team,

I Have noticed that when the block is in mobile view the side dive images should get re-size but it's not happening in EDS. Please check the below snaps and do what is needed.

![image](https://github.com/hlxsites/aldevron/assets/117751754/ca39d3e1-42a8-4465-9e12-96ca87d3506d)
![image](https://github.com/hlxsites/aldevron/assets/117751754/2d9e78e1-93f2-4185-9cd0-a606f372690a)

**Comment by gowtamibetireddy** [comment]
@Kummu007 please check now
![Uploading image.png…]()

**Comment by Kummu007** [comment]
Hi @gowtamibetireddy  thanks for the update, this is working as expected but identified a new issue in the padding. In the legacy the bottom padding is 30px but we are not to notice the same in the EDS. Please look into the below snap.

https://www.aldevron.com/
https://main--aldevron--hlxsites.hlx.page/qe-test/articalcards

![image](https://github.com/hlxsites/aldevron/assets/117751754/0337cedf-51b9-43d6-9fd8-2030f654a856)

![image](https://github.com/hlxsites/aldevron/assets/117751754/53fabc74-6ddc-47f7-a1e7-85ce823fd695)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
This is working as expected, hence closing the ticket.

![Uploading image.png…]()
