### ISSUE TITLE
Article cards- Block Padding Issue 

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#104]
Hi Team,

There is a padding issue for the entire block. In Legacy, the padding is 80 but in EDS it is only 60. Please check the below snap and do the needful.

![image](https://github.com/hlxsites/aldevron/assets/117751754/b05ff061-e099-47fc-8b91-e512f8dd5e83)

![image](https://github.com/hlxsites/aldevron/assets/117751754/e4a9e289-ad1d-4104-b1d9-c9967f5b8a14)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
This is working as expected, hence closing the issue.

![image](https://github.com/hlxsites/aldevron/assets/117751754/193f9281-86a4-43bb-ab5d-75b7d3064ba6)
