### ISSUE TITLE
Article cards- H2 Padding Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#105]
Hi Team,

There is a padding issue for the H2 title. In Legacy, the padding top is zero but in EDS the padding top is 30px. Please check the below snap and do what is needed.

![Article card h2 padding-EDS](https://github.com/hlxsites/aldevron/assets/117751754/8abb9636-9f67-4480-af12-4feb435573dc)

![Article card h2 padding-legacy](https://github.com/hlxsites/aldevron/assets/117751754/94ed15fe-6869-4c88-836e-5bff5d9ce932)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
This is working as expected, hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/8315a3c3-87be-4254-9bc1-31f969697d1b)
