### ISSUE TITLE
hero-carousel-component

### ISSUE THREAD

**Issue by teshukatepalli1** [hlxsites/aldevron#108]
this carousel component is used on main page that can be used for rendering images and content on the image with some buttons to displat the content as carousels

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate.

**Comment by Kummu007** [comment]
Hero Carousel- Mouse cursor swipe control Issue #195
Hero Carousel- Mobile View issue #179

**Comment by Kummu007** [comment]
This is working as expected, except The Mouse cursor swipe control will be taken care of in phase 2

Hero Carousel- Mouse cursor swipe control Issue #195
