### ISSUE TITLE
Article card With Sideline Alignment and H2 issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#110]
Hi Team, 

There is an issue in the H2 and alignment.

1. The provided h2 title is appearing on the screen
2. there is an alignment issue 

Please look into the below snaps and do what is needed

![image](https://github.com/hlxsites/aldevron/assets/117751754/4e0442b7-11c2-451a-b0ef-5ab41e6167fb)

![image](https://github.com/hlxsites/aldevron/assets/117751754/0a8e31e0-5ea9-4db5-8d23-ce29a1bddb41)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
@Vinaykumargujja  please look into the below snap, the bullet points are disturbing the content.

![image](https://github.com/hlxsites/aldevron/assets/117751754/7bec6181-b479-49d3-b035-6aa930740351)
