### ISSUE TITLE
Article card Description padding issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#111]
Hi Team, 

There is an issue in the description padding where in the legacy it is 0.5em but in the EDS it is showing as 0.6em. Please look into the below SS and do what is needed.

![Article card des padding-eds](https://github.com/hlxsites/aldevron/assets/117751754/88105194-ab6e-427c-84cb-efbc43980eea)
![Article card des padding-legacy](https://github.com/hlxsites/aldevron/assets/117751754/f281ff08-ae87-4a24-9617-872c04b03533)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
@Vinaykumargujja thanks for the update, this is working as expected. Hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/fcee9adc-f887-4611-b4a5-030653bec7eb)
