### ISSUE TITLE
Timeline slider

### ISSUE THREAD

**Issue by teshukatepalli1** [hlxsites/aldevron#116]
Here we need to implement the timeline slider. 

When we click on year it should scroll to teir respective container in the same way we need to create another container for the content of the slider that shoild be available to the bottom of the yearly slider. 

There should be arrows to move slide left or right.

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
@teshukatepalli1 please add an author guide in the ticket.

**Comment by pardeepgera23** [comment]
Hi @Kummu007 

Please refer to below for authoring of this block and validate :

<img width="700" alt="image" src="https://github.com/hlxsites/aldevron/assets/147177349/509e7ea9-b87c-4d31-9b1a-5832836c07f1">

**Comment by Kummu007** [comment]
This is working as expected, except The Mouse cursor swipe control will taken care in phase 2 

Hero Carousel- Mouse cursor swipe control Issue #195
