### ISSUE TITLE
Footer - Twitter Logo update

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#118]
Hi Team,

As we all know the Twitter logo has been updated from a bird called Larry to an X. So, please make the changes accordingly in the footer.

![image](https://github.com/hlxsites/aldevron/assets/117751754/3ad6e648-3fb6-40b6-b78e-8dd462585fb1)

![image](https://github.com/hlxsites/aldevron/assets/117751754/a9faed65-2ac1-456b-b8d4-f2b68210b079)

**Comment by pardeepgera23** [comment]
@Kummu007 - please validate

**Comment by Kummu007** [comment]
Hi @Vinaykumargujja thanks for the quick response, This issue is fixed hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/005d77b2-029f-4aa7-a570-8edebf47cc35)


![image](https://github.com/hlxsites/aldevron/assets/117751754/6ea27d95-01ba-49ca-9d0e-5eb71c0053a3)
