### ISSUE TITLE
Hero banner-CTA button tooltip

### ISSUE THREAD

**Issue by Vinaykumargujja** [hlxsites/aldevron#124]
There is no tooltip for the button/anchor for the hero banner button in EDS.
![image](https://github.com/hlxsites/aldevron/assets/148342791/cc995350-6cb3-459c-851a-a547e93d7269)

Latest CTA- tooltip for reference:
![image](https://github.com/hlxsites/aldevron/assets/148342791/e4495803-5d1f-46dd-802f-6730d03dfb8d)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
This is working as expected.
