### ISSUE TITLE
Zoomed image

### ISSUE THREAD

**Issue by teshukatepalli1** [hlxsites/aldevron#125]
This ticket is related to modal that renders the image which is available on content structure. 

- Once the image is clicked it should display on modal 
- After that there is an another zoom functionality to zoom more. Here we are making consistant  across the platform. First level is 100% image and second level is 150% image
- Once the image is displayed there will be closed by close button or outside the modal box.

**Comment by pardeepgera23** [comment]
@Kummu007 / @mooresindhuja - FYI.

**Comment by Kummu007** [comment]
This is working as expected.
