### ISSUE TITLE
Category pages variations

### ISSUE THREAD

**Issue by teshukatepalli1** [hlxsites/aldevron#129]
This Category is related to configuration. Here there are 3 variations with colors

-  plasmids
-  proteins
-  mrna

**Comment by pardeepgera23** [comment]
@Kummu007 / @mooresindhuja  - Categories have been defined for applying color scheme to pages. Please validate and author the pages with appropriate category applied to pages.

**Comment by Kummu007** [comment]
This is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/36063811-f5bd-4365-948a-70122e2d743b)

![image](https://github.com/hlxsites/aldevron/assets/117751754/c2c137bf-1ae0-4ced-9ac9-98878bb1f3ca)

![image](https://github.com/hlxsites/aldevron/assets/117751754/641e6001-a078-44c7-9d4c-1e044bff184a)

![image](https://github.com/hlxsites/aldevron/assets/117751754/5e4bfda2-c364-4105-ab9c-0ae9227cf1d7)

![image](https://github.com/hlxsites/aldevron/assets/117751754/562b0531-9770-45b8-b4c0-b8478b82b227)

![image](https://github.com/hlxsites/aldevron/assets/117751754/12b8fcec-5d62-40c5-b011-bc94c32b7d20)
