### ISSUE TITLE
Tabs - CTA/New Tab

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#131]
Hi Team, 

I have noticed that there were a few CTA that should open in the new tabs but that is happening in the EDS tabs block.

@teshukatepalli1  as discussed please look into this and do the needed.

https://main--aldevron--hlxsites.hlx.page/qe-test/tab

https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate

**Comment by Kummu007** [comment]
@teshukatepalli1  can you please add the author guide.

**Comment by pardeepgera23** [comment]
Hi @Kummu007 

Please check the authoring details here. **/qe-test/tab**

**Comment by pardeepgera23** [comment]
@Kummu007 - Please connect with Sindhuja on how to author it for new tab and validate it.

**Comment by Kummu007** [comment]
This is working as expected.

Note:- If the URL needs to open in the new tab then we have to add a link and bold the text.
