### ISSUE TITLE
Tabs - Background Color

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#132]
Hi Team,

I have noticed that the below-given legacy site has a background color of  #fff1e2 is a light pastel color that is not able to be added in the EDS. Please go through the below URL.

@teshukatepalli1  As discussed please look into this 

https://www.aldevron.com/standardized-cell-and-gene-therapy-products

https://main--aldevron--hlxsites.hlx.page/qe-test/tab

**Comment by teshukatepalli1** [comment]
Hi @Kummu007  As discussed with the client table background colors are not required. We are making consistant across the site. Please verify again and close this ticket

**Comment by Kummu007** [comment]
@teshukatepalli1  thanks for the update, Closing this ticket.

@pardeepgera23  @gowtamibetireddy  FYR
