### ISSUE TITLE
Tabs - List order Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#133]
Hi Team, 

There is an issue with the order list.

The data needs should be in the same list order but in the second paragraph with the same bullet point as the below snap.

![Article card list issue](https://github.com/hlxsites/aldevron/assets/117751754/ca5b66be-8067-40cd-8241-ff281b440276)

 But it's not happening in the EDS.

@teshukatepalli1  as discussed please look into this

**Comment by pardeepgera23** [comment]
@kummu - Please validate

**Comment by Kummu007** [comment]
This is working as expected. Hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/dbdd237b-1d91-4ba0-a99d-86acdf3fdd57)
