### ISSUE TITLE
Tabs - Alignment Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#134]
Hi Team, 

I have noted that there is an alignment issue with a table that is added in the tabs block. Please look into the below snaps.

https://main--aldevron--hlxsites.hlx.page/qe-test/tab
https://www.aldevron.com/standardized-cell-and-gene-therapy-products

![image](https://github.com/hlxsites/aldevron/assets/117751754/01afd01c-62f1-41ef-843d-df0bfd772c81)

![image](https://github.com/hlxsites/aldevron/assets/117751754/b2fc6610-b4fd-4780-acf7-43782ec0ca66)

![image](https://github.com/hlxsites/aldevron/assets/117751754/66193c7b-8e87-4679-8d31-59de29761bcd)

@teshukatepalli1  as discussed please look into this and do the needful.

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate

**Comment by Kummu007** [comment]
This is working as expected, 

![image](https://github.com/hlxsites/aldevron/assets/117751754/a0e83268-a532-4719-9758-6efcafdb0fb8)


![image](https://github.com/hlxsites/aldevron/assets/117751754/c7c2e9af-5952-43ab-a097-1571b8d1f8b7)
