### ISSUE TITLE
Create block for Audio Embed

### ISSUE THREAD

**Issue by pardeepgera23** [hlxsites/aldevron#138]
**Summary**

Create a block to embed audio content from buzzsprout.com

Refer to example from below link - 
https://www.aldevron.com/listen-to-shortening-the-time-from-start-to-finish

**Comment by pardeepgera23** [comment]
@Kummu007 / @mooresindhuja  - Block for Audio Embed from buzzsprout.com

**Comment by pardeepgera23** [comment]
**Authoring details:**    Refer to **/test/audio-embed.docx**

![image](https://github.com/hlxsites/aldevron/assets/147177349/cab2e84a-bdd7-42d5-9217-eed0352ffbd7)

**Comment by Kummu007** [comment]
This is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/cf603352-f60c-462b-9cc2-6a5aafbcd60c)
