### ISSUE TITLE
Footer - Social Media icons

### ISSUE THREAD

**Issue by gowtamibetireddy** [hlxsites/aldevron#141]
Hi Team,

Please add and arrange the footer social media icons as per the below snap.
Desktop:
![image](https://github.com/hlxsites/aldevron/assets/147179869/681c56bb-f1bd-4460-8d7a-163d6f2a123d)
Mobile:
![image](https://github.com/hlxsites/aldevron/assets/147179869/0c708e30-e608-46af-b364-3194b26529b2)

**Comment by Kummu007** [comment]
This is a duplicate of issue 40
