### ISSUE TITLE
Create articlecards Block

### ISSUE THREAD

**Issue by gowtamibetireddy** [hlxsites/aldevron#15]
Feature Requirement:
Article Cards
User Story: Article cards block is used to author the image, main title, text link, description to show it as an article card.
It has 2 variations as of now.
1. Without sideline
https://www.aldevron.com/
![image](https://github.com/hlxsites/aldevron/assets/147179869/723fd511-eeb6-472e-aa35-3ea7af142d21)
2. With sideline
https://www.aldevron.com/campus
![image](https://github.com/hlxsites/aldevron/assets/147179869/29e1cae8-852f-40cf-85b6-1b56e93ecb31)
Success Criteria:
The component should be display as expected in Aldevron site, in desktop, tablet and mobile views.

Authoring guide:
Without sideline:-
1. Insert a table with three rows. (first row - full width, second & third row - 3 x 3)
2. In the first row, provide the name of the block along with the class name in brackets as shown here. "articlecards (outer)"
3. In the second row first column, provide the main title(only in first column - Ex - Recent News), image, text link, description. Repeat the same in 2nd and 3rd columns. 
Note: In Second row, each column must contain left side div content as shown in the below.
![image](https://github.com/hlxsites/aldevron/assets/147179869/f88288f4-b3cc-409e-bcf1-98bfc997db66)

4. In the third row first column,  provide the main title(only in first column - Ex - Recent Blog Posts), image, text link, description. Repeat the same in 2nd and 3rd columns. 
Note: In Third row, each column must contain right side div content as shown in the below.
![image](https://github.com/hlxsites/aldevron/assets/147179869/fa3f2e8c-174e-4c50-be00-3521f7e3eeba)
Ref authoring url: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BC1FCFE29-A3EE-4097-8FBD-581FDE3BF3D7%7D&file=col-block-test.docx&action=default&mobileredirect=true

With sideline:-
1. Insert a table with three rows. (first row - full width, second & third row - 3 x 3)
2. In the first row, provide the name of the block in brackets as shown here. "articlecards"
3. In the second row first column, provide the main title(only in first column - Ex - Related News), image, text link, description. Repeat the same in 2nd and 3rd columns. 
![image](https://github.com/hlxsites/aldevron/assets/147179869/4580fe5f-2839-4790-8c57-5d2eada01c46)

4. In the third row first column,  provide the main title(only in first column - Ex - Recent Blog Posts), image, text link, description. Repeat the same in 2nd and 3rd columns. 
Note: In Third row, each column must contain right side div content as shown in the below.
![image](https://github.com/hlxsites/aldevron/assets/147179869/8d0967e6-bfc7-4f55-ac4e-a076aef0fe74)

5. ** Add the metadata table as shown below ** Sideline will not be shown if the below table is not added in the doc.
![image](https://github.com/hlxsites/aldevron/assets/147179869/21aa724e-86f3-4f0a-a5d9-c28d2ef8bdbb)

**Comment by HimanshuChauhan06** [comment]
@gowtamibetireddy Hi! I have added the steps to create 2 and 4 column blocks. Please have a look.

**Steps for creating 2 column block.**
1. Create a 2 rows table and split the 2nd row into 2 columns.
![image](https://github.com/hlxsites/aldevron/assets/147372269/e7585789-9bc7-48e7-8c75-ed21eaac55a5)

2. Add "articlecards (columns-2, pt-80,bg-grey) " in the 1st row.
![image](https://github.com/hlxsites/aldevron/assets/147372269/82bc1768-e7d5-4962-bc23-c15cfbebbd4e)

3. Add a Title to both columns.
![image](https://github.com/hlxsites/aldevron/assets/147372269/360382ec-fb43-438c-b673-3b9b3a797559)

4. Add Images.
![image](https://github.com/hlxsites/aldevron/assets/147372269/d5eeb60b-ecc9-4df6-a876-7e2b9725e4e2)

5. Create a link.
![image](https://github.com/hlxsites/aldevron/assets/147372269/7bbbaee2-f411-4d1d-b82a-1bae473dc2b7)

6. Add description.
![image](https://github.com/hlxsites/aldevron/assets/147372269/caa36c28-403d-498c-ac6d-2da47c4e57a6)

**Steps for creating a 4 column block.**
1. Create a 2 rows table and split the 2nd row into 2 columns.
![image](https://github.com/hlxsites/aldevron/assets/147372269/e7585789-9bc7-48e7-8c75-ed21eaac55a5)

2. Add "articlecards (columns-4, horizontal, bg-grey)  " in the 1st row.
![image](https://github.com/hlxsites/aldevron/assets/147372269/3d60b05f-05d1-4b00-92c3-26616e2e11d4)

3. Add Images.
![image](https://github.com/hlxsites/aldevron/assets/147372269/85f70bf6-10aa-4a23-8bba-6745fb6bfa28)

4. Create a link.
![image](https://github.com/hlxsites/aldevron/assets/147372269/0ec43c5d-b28a-4800-9832-3b77d20eaab0)

5. Add description.
![image](https://github.com/hlxsites/aldevron/assets/147372269/5e105389-afc7-4cd3-8f6f-b20aebd904a2)

6. Create another 2 rows table and split the 2nd row into 2 columns. 
![image](https://github.com/hlxsites/aldevron/assets/147372269/10a42ee7-226f-4158-82e5-3eb5b0916a3f)

7. Put "articlecards (columns-4, horizontal, bg-grey)  " in the 1st row.
![image](https://github.com/hlxsites/aldevron/assets/147372269/fd57c614-1601-482e-ad32-e33eb03eeb09)

8. Add Images
![image](https://github.com/hlxsites/aldevron/assets/147372269/2100899a-5099-4421-8120-20eb268db563)

10. Create a link.
![image](https://github.com/hlxsites/aldevron/assets/147372269/aab23eae-fd1a-4368-ae7e-6a8a61f677ae)

11. Add description.
![image](https://github.com/hlxsites/aldevron/assets/147372269/a1aaf86f-528d-4003-9931-5cee0cc68f8f)

**Comment by pardeepgera23** [comment]
@Kummu007 - This has been merged to main. Please validate.

**Comment by gowtamibetireddy** [comment]
@Kummu007 Its ready for QA on feature branch. It will be merged to main.
https://feature-ac-sideline-variation--aldevron--hlxsites.hlx.page/test/campus
https://feature-ac-sideline-variation--aldevron--hlxsites.hlx.page/test/col-block-test
 https://main--aldevron--hlxsites.hlx.page/test/campus
https://main--aldevron--hlxsites.hlx.page/test/col-block-test

**Comment by pardeepgera23** [comment]
@Kummu007 / @mooresindhuja  / @gowtamibetireddy - This has been merged to main

**Comment by Kummu007** [comment]
This entire story is going to be rewritten. Hence closing this and all related bugs.
