### ISSUE TITLE
Model-image(Zoomed Image)-Full screen issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#151]
Hi Team, 

I have noted that when we click on the image it should open in the full screen but it's not happening in the legacy. Please look into the below snap and do the needful.

https://www.aldevron.com/our-services/gene-synthesis

https://main--aldevron--hlxsites.hlx.page/qe-test/zoomed-image

![image](https://github.com/hlxsites/aldevron/assets/117751754/175c057e-f2f2-4768-b4fd-2086ea9de1c0)

![image](https://github.com/hlxsites/aldevron/assets/117751754/9cf03a4f-ab55-484a-baa2-d7a1f302265c)

![image](https://github.com/hlxsites/aldevron/assets/117751754/6dafd711-d7bc-42f3-82be-ec9d5a47397a)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
@Vinaykumargujja  as discussed please look into this and do the needful

**Comment by teshukatepalli1** [comment]
Hi @Kummu007  THis is the width we can accomodate in first zoom. Fr second level of zoom we are giving 150% by default to get the zoomed functionality. This 2 level zooms are by default.

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate again and connect with Vinay/Teshu if the issue still persists.

**Comment by Vinaykumargujja** [comment]
@Kummu007 , Fixed hid the zoom icon after the zoom.
Fixed padding, font-size, border-radius issues for close and zoom icons

**Comment by Kummu007** [comment]
This is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/6b7cba2d-5245-4506-9a9c-3c29a004dfac)
