### ISSUE TITLE
Audio Embed Padding Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#153]
Hi Team, 

There is a padding issue in this block. Please look into the below snap and do the needful.

https://www.aldevron.com/listen-to-shortening-the-time-from-start-to-finish
https://main--aldevron--hlxsites.hlx.page/qe-test/audio-embed

![Audio](https://github.com/hlxsites/aldevron/assets/117751754/9498973d-2e1d-4bea-848c-0d3c5d3a3516)

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate

**Comment by Kummu007** [comment]
This is working as expected, hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/7ca1abff-f548-4a4d-9017-b41aafa2d60d)
