### ISSUE TITLE
Audio Embed- Small Player CSS issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#156]
Hi @teshukatepalli1 

As discussed please look into this.

https://assets.buzzsprout.com/assets/players/small-player-beta-fe35b7356fc8aaffc997f2a8c341187310d07ab5e2a2053eae6fc3c926413720.css

**Comment by ssahoo1996** [comment]
It's fixed via #153 . @Kummu007 Please check and confirm.
