### ISSUE TITLE
Video Banner- Mobile View Background video issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#157]
Hi Team, 

On the mobile view, I have noticed that the background video for the Video Banner block is not playing.

Please refer to the URL and snapshots

https://main--aldevron--hlxsites.hlx.page/qe-test/video-banner-25
https://www.aldevron.com/25th-anniversary

![image](https://github.com/hlxsites/aldevron/assets/117751754/5e7d9784-6ae4-48bc-884f-d1ad22a2b6bb)

![image](https://github.com/hlxsites/aldevron/assets/117751754/2e85383b-3b3e-44bf-b434-2a4b6ae4441d)

**Comment by pardeepgera23** [comment]
Hi Kumaresan,

This is agreed with Client and in mobile view, we are using background image and not playing video for performance gain.

**Comment by Kummu007** [comment]
As per the above thread, we are using background image and not playing video for performance gain.

Hence closing the ticket.
