### ISSUE TITLE
Video Embed (YouTube)- Border and fast forward 5sec is not working

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#158]
Hi Team, 

I have noted there is an issue at the border and YouTube fast forward 5sec is not working.

@teshukatepalli1 as discussed, please look into this and do the needful.

https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid

https://main--aldevron--hlxsites.hlx.page/qe-test/video

![Uploading Video-EDS border.png…]()

**Comment by pardeepgera23** [comment]
@Kummu007 / @ssahoo1996 - Please validate

**Comment by Kummu007** [comment]
This is working as expected. Hence closing the ticket.
