### ISSUE TITLE
 Vimeo video player- Div width and height and fast forward 5secs issue 

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#159]
Hi Team, 

I have noticed that there is an issue with the div length and width and fast forward 5 sec is not working. Please look into the below and do the needful.

![image](https://github.com/hlxsites/aldevron/assets/117751754/a75083b0-6eff-4edb-872b-90cc0a7ffd46)

![image](https://github.com/hlxsites/aldevron/assets/117751754/6042d2c1-4d5a-4c22-a739-678a43e5555c)

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate

**Comment by ssahoo1996** [comment]
@Kummu007 We need to remove 'outer' from the doc heading to get the video in fullscreen and need to add it if we don't want the video in fullscreen (e.g. Vimeo(outer) ).

**Comment by Kummu007** [comment]
@ssahoo1996 thanks for the update, this is working as expected hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/00cf4da1-154a-4db2-88d8-e8e27fdd5357)
