### ISSUE TITLE
Minor issues in Website Pages 

### ISSUE THREAD

**Issue by mooresindhuja** [hlxsites/aldevron#167]
**1. Left and top headings text for table needs to be in white color. Also, Table is not appearing properly.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/e65c24bc-c371-4565-a52f-2a233c60eea0)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/3235eefe-9c24-45d7-b6d9-21e7277bb58a)
**reference link**: https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid
**2. Learn more button in Table is having difference in font size.**
Please refer to screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/97d33cde-b548-4f9b-bdc4-8beba0ac5eec)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/f44d6a07-1f66-4c9a-89fb-fbb892f3e824)
**reference link**: https://www.aldevron.com/platforms/mrna-production
**3. Difference in font-size is there for text in Aldevron.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/d9647a93-3866-481f-a572-b85783dbfb78)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/2b03dee6-7ac5-4fbc-be8d-9624015778c3)
**reference link**: https://www.aldevron.com/service/custom-protein-services
**4. No margin for columns block.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/d9065fdd-75b6-4e09-8022-d27cc192ef59)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/05c0cf7d-ee6d-47ec-964c-72c688549e40)
**reference link**: https://www.aldevron.com/platforms/plasmid-dna-production
**5. After applying Italic style to hyperlinks starting in a fresh line are having font-size and alignment issues.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/b115a9da-c41b-4b77-bdd0-46d03b178975)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/eba18e54-0821-4dba-a99a-65fbdcbe9b3c)
**reference link**: https://www.aldevron.com/resources/references
**6. Italic text is not appearing properly in Hero banner.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/722eb588-acb2-4567-8466-abebe0b43aa4)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/5abab2ab-1b13-4b5e-bbc7-eebcaeb2b4d6)
**reference link**: https://www.aldevron.com/products/cas9/spyfi-nuclease
**7. Spacing issues for Column Images component.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/d4e9778f-8f85-479a-83ca-1de5a045435b)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/53474984-ce5e-4820-a63a-b972e39aa285)
**reference link**: https://www.aldevron.com/resources/product-guides
**8. Alignment issue for columns block**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/01a90297-5564-40e9-8ef3-e5e66811026b)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/f63df387-23a3-455b-acd5-4316d57c242f)
**reference link**: https://www.aldevron.com/campus/advance-campus-fargo
**9. Bullets are aligned in a different manner in Aldevron.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/405e0392-b527-4f63-91f6-6a1b641eb955)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/4727b43e-95fd-49d3-a00f-19ca8e6694cb)
**reference link**: https://www.aldevron.com/aldevron-california-consumer-rights-notice
**10. Text is aligned to right in Aldevron**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/a0ba8fa9-929b-4a8f-904c-89217377bdd3)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/7fee0eb9-bf67-485b-9aaa-c5a740ec2b9f)
**reference link**: https://www.aldevron.com/terms
**11. Text is not coming full width for RTE.**
Please refer to the screenshots below and reference link:
**Preview:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/23c20158-642a-4fe7-bdb2-c50344b2fbd8)
**In Aldevron:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/556c497e-3dd0-4344-8692-5b9f5eee9f26)
**reference link**: https://www.aldevron.com/terms

**Comment by Kummu007** [comment]
All these observations have been taken care of. Hence closing the ticket.
