### ISSUE TITLE
News Pages issues

### ISSUE THREAD

**Issue by HimanshuChauhan06** [hlxsites/aldevron#168]
**1. Hyperlink image needs to be center aligned.**

- Aldevron URL:- https://www.aldevron.com/about-us/news/webinar-crispr-cures-2033-gene-editing

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/webinar-crispr-cures-2033-gene-editing

**2.  Hyperlink image and "Watch On Demand" button url should open in new tab as per Aldevron website.**

- Aldevron URL:- www.aldevron.com/about-us/news/webinar-comprehensive-gmp-manufacturing-of-mrna-lnp-drug-products-sequence-to-vial

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/webinar-comprehensive-gmp-manufacturing-of-mrna-lnp-drug-products-sequence-to-vial

**3. Difference in font-size is there for text in Aldevron.**

- Aldevron URL:- https://www.aldevron.com/about-us/news/idt-aldevron-partnership

![image](https://github.com/hlxsites/aldevron/assets/147372269/c0f2e11d-a2eb-4fd3-aace-4cdc328df7ad)

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/idt-aldevron-partnership

**4. Date below the images needs to be center aligned on the following pages: -**

- Aldevron URL:- www.aldevron.com/about-us/news/webinar-comprehensive-gmp-manufacturing-of-mrna-lnp-drug-products-sequence-to-vial

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/webinar-comprehensive-gmp-manufacturing-of-mrna-lnp-drug-products-sequence-to-vial

- Aldevron URL:- www.aldevron.com/about-us/news/how-a-sponsored-cmc-platform-accelerates-mrna-projects-to-the-clinic

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/how-a-sponsored-cmc-platform-accelerates-mrna-projects-to-the-clinic

-Aldevron URL:-  www.aldevron.com/about-us/news/webinar-genome-editing-tools-beyond-discovery
 
- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/webinar-genome-editing-tools-beyond-discovery

-Aldevron URL:-  www.aldevron.com/about-us/news/webinar-can-a-small-plasmid-produce-huge-benefits-the-power-of-small

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/webinar-can-a-small-plasmid-produce-huge-benefits-the-power-of-small

- Aldevron URL:- www.aldevron.com/about-us/news/webinar-advanced-plasmid-technology-improving-safety-and-performance

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/webinar-advanced-plasmid-technology-improving-safety-and-performance

- Aldevron URL:- www.aldevron.com/about-us/news/mrna/sarna-manufacturing-webinar-considerations-to-accelerate-the-path-to-clinic
 
- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/sarna-manufacturing-webinar-considerations-to-accelerate-the-path-to-clinic

- Aldevron URL:- www.aldevron.com/about-us/news/how-a-sponsored-cmc-platform-accelerates-mrna-projects-to-the-clinic 

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/how-a-sponsored-cmc-platform-accelerates-mrna-projects-to-the-clinic

**5. "REGISTER" button's url should open in a new tab as per Aldevron website on the following pages:-**

Aldevron URL:-
- www.aldevron.com/about-us/news/expanded-focus-on-cmc-in-gene-cell-therapy-development
- www.aldevron.com/about-us/news/how-a-sponsored-cmc-platform-accelerates-mrna-projects-to-the-clinic

Authoring Page URL;- 

- https://main--aldevron--hlxsites.hlx.page/news/expanded-focus-on-cmc-in-gene-cell-therapy-development
- https://main--aldevron--hlxsites.hlx.page/news/how-a-sponsored-cmc-platform-accelerates-mrna-projects-to-the-clinic

**6. Hyperlink Image url should open in new tab as per Aldevron website.**

- Aldevron URL:-  www.aldevron.com/about-us/news/advancing-direct-enzyme-delivery-for-therapeutic-genome-editing-in-vivo

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/advancing-direct-enzyme-delivery-for-therapeutic-genome-editing-in-vivo

**7. Video layout needs to be smaller as per aldevron website.**

- Aldevron URL:- www.aldevron.com/about-us/news/aldevron-announces-expansion-of-mrna-production-capability

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/aldevron-announces-expansion-of-mrna-production-capability

**8. Video and Image needs to be center aligned on the following pages:-**

- Aldevron URL:-  www.aldevron.com/about-us/news/aldevron-receives-spotlight-at-2021-state-of-the-state-address-for-its-40-plus-covid-19-programs

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/aldevron-receives-spotlight-at-2021-state-of-the-state-address-for-its-40-plus-covid-19-programs

- Aldevron URL:- www.aldevron.com/about-us/news/aldevron-receives-premier-technology-business-award

- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/aldevron-receives-premier-technology-business-award

**9.  Links at the bottom of the pages are appearing as Buttons.**

- Aldevron URL:- www.aldevron.com/about-us/news/kevin-ballinger-to-assume-ceo-role-at-aldevron-michael-chambers-to-become-executive-chairman
- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/kevin-ballinger-to-assume-ceo-role-at-aldevron-michael-chambers-to-become-executive-chairman
-Aldevron URL:- www.aldevron.com/about-us/news/plasmid-manufacturer-scales-up-production-capacity-to-serve-new-therapeutics
- Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/plasmid-manufacturer-scales-up-production-capacity-to-serve-new-therapeutics
- Aldevron URL:- www.aldevron.com/about-us/news/in-the-news-bloomberg-law-aldevron-taps-legal-chief-looks-for-possible-covid-vaccine-role
Authoring Page URL;- https://main--aldevron--hlxsites.hlx.page/news/in-the-news-bloomberg-law-aldevron-taps-legal-chief-looks-for-possible-covid-vaccine-role

**Comment by Kummu007** [comment]
All these are working as expected. Hence closing the ticket
