### ISSUE TITLE
Image Thumbnail Slider- Mobile View issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#177]
Hi Team I have noticed that there is a re-sizing issue when the block is in mobile view.

Please look into the below snap and do the needful

https://main--aldevron--hlxsites.hlx.page/qe-test/image-thumbnail-slider

https://www.aldevron.com/campus

![Image slide LEGACY](https://github.com/hlxsites/aldevron/assets/117751754/ad85b6f4-5702-4ffa-bc26-370fb03dbe75)
![Image slide EDS](https://github.com/hlxsites/aldevron/assets/117751754/fe14c3a2-3bca-4740-9b53-0de60c10de6a)

**Comment by pardeepgera23** [comment]
Hi Kumaresan - After changing the viewport to mobile view, please refresh the page and images will resize.

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate
