### ISSUE TITLE
Image Thumbnail Slider- Image overriding

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#178]
Hi Team, 

I have noticed that there is an issue when the view is switching from mobile to desktop and the same image is not reflecting.

Please look into the below snap and do the needful.

![image](https://github.com/hlxsites/aldevron/assets/117751754/3ec3ae60-3823-439b-85c9-7779e4416e11)
![Image slide EDS alignment](https://github.com/hlxsites/aldevron/assets/117751754/df9f436a-49f8-400e-baa7-c97b38a9de19)

**Comment by pardeepgera23** [comment]
@Kummu007  - Please refresh the page after changing the viewport from mobile to desktop or vice-versa.
