### ISSUE TITLE
Timeline slider-Year Div Width issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#185]
Hi Team, 

I have noticed that the width of a year div should be 160 but in EDS it is only 130. Please look into the below snap and do the needful.

https://main--aldevron--hlxsites.hlx.page/test/timeline-slide

https://www.aldevron.com/25th-anniversary

![image](https://github.com/hlxsites/aldevron/assets/117751754/28a1f5d1-4713-454c-aee9-07f2ed0fc1c4)

![image](https://github.com/hlxsites/aldevron/assets/117751754/bb1084b8-6139-4216-a70a-b7628b0c6c1c)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate
