### ISSUE TITLE
Timeline slider - Mouse swipe control

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#187]
@teshukatepalli1  as discussed please look into this swipe control issue.

https://main--aldevron--hlxsites.hlx.page/test/timeline-slide

https://www.aldevron.com/25th-anniversary

**Comment by pardeepgera23** [comment]
@Kummu007 - please validate and connect with Vinay if the issue still persists

**Comment by Kummu007** [comment]
@pardeepgera23  this is not working as expected. @Vinaykumargujja  please check this once

**Comment by pardeepgera23** [comment]
Hi Kumaresan - As discussed with Client, they are ok with this. It can be taken as an enhancement in Phase 2.

**Comment by Kummu007** [comment]
As per the above thread, the Clients are okay with this in this Phase. It can be taken as an enhancement in Phase 2. Hence closing the the ticket,
