### ISSUE TITLE
Accordion Transition Effect Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#193]
Hi Team,

I have noticed that the animation effect is missing for the Accordion block. Please compare the site with Legacy.

https://main--aldevron--hlxsites.hlx.live/qe-test/accordion-test

https://www.aldevron.com/products/cas9

**Comment by pardeepgera23** [comment]
Hi @Kummu007 ,

As discussed with client, we can ignore this and close this issue.

**Comment by Kummu007** [comment]
The client is okay with this effect. Hence closing the ticket.
