### ISSUE TITLE
Table(heading-top, heading-left,outer)

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#194]
@teshukatepalli1  as discussed, please look into the cell colors in the below snap and do the needful.

https://main--aldevron--hlxsites.hlx.page/qe-test/table-heading-top-heading-left-outer

https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid

![image](https://github.com/hlxsites/aldevron/assets/117751754/4aad6e2b-3369-496f-be66-845c555d1ee8)

![image](https://github.com/hlxsites/aldevron/assets/117751754/ece30ad2-f301-436d-9df1-2cea5d3e981d)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
@teshukatepalli1  thanks for the update this is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/06ff4759-0186-42cb-bfe4-94611ce1861e)
