### ISSUE TITLE
Header-Cart-Icon, Count and Total are missing 

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#20]
Hi Team,

While comparing the developed header block with the legacy site header block, I noticed that the Cart-Icon, Count and Total are missing in the header

Please have a glimpse at the below snapshot

![image](https://github.com/hlxsites/aldevron/assets/117751754/1636f68e-01be-49d2-b865-80eef4189a7b)
![image](https://github.com/hlxsites/aldevron/assets/117751754/4ea39926-dedb-4a93-a6ed-27d4f03f84a3)
![image](https://github.com/hlxsites/aldevron/assets/117751754/3cd5ec57-4efe-442a-98ab-cd3f95c30856)
![image](https://github.com/hlxsites/aldevron/assets/117751754/9b700c54-44ca-420f-a361-37af4a490330)

**Comment by pardeepgera23** [comment]
As confirmed with the client in last demo, this is out of scope. Please close this issue.

**Comment by Kummu007** [comment]
@pardeepgera23 Thanks for the update.

As mentioned in the above thread, this is not in scope. Hence closing the ticket.
