### ISSUE TITLE
Sidebar navigation- Hide and show effect is missing

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#206]
Hi Team,

I have noticed that the hide-and-show effect is missing for the navigation sidebar. Please compare the below links and do the needful.

https://main--aldevron--hlxsites.hlx.page/custom-manufacturing/mrna-production/drug-substance

https://www.aldevron.com/our-services/research-grade

**Comment by teshukatepalli1** [comment]
Hi @Kummu007 . This is expected behaviour as per the previous discussions with the client. Please consider this as feature. 
Assigning back to you for other validations.
