### ISSUE TITLE
Sidebar Navigation- Paddng issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#207]
Hi Team, 

I have noticed that there is a padding issue in the sidebar navigation. Please look into the below snap and do the needful.

https://www.aldevron.com/our-services/cas9/ribonucleoproteins

https://main--aldevron--hlxsites.hlx.page/custom-manufacturing/mrna-production/design-and-development

![image](https://github.com/hlxsites/aldevron/assets/117751754/b94e4375-cd7a-406c-b9b1-346dc28ec64a)

![image](https://github.com/hlxsites/aldevron/assets/117751754/2ee09760-6fc5-4823-8f34-bc8637777b01)

**Comment by teshukatepalli1** [comment]
Hi @Kummu007  I fixed the issue please look into it

**Comment by Kummu007** [comment]
This is working as expected. 

![image](https://github.com/hlxsites/aldevron/assets/117751754/8f3fb3a4-1e9e-4912-8c0f-6e2a485aa229)
