### ISSUE TITLE
Header--Mobile View-- Header menu should open in accordion mode and News should be in BOLD(font)

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#21]
Hi Team,

While comparing the developed header block with the legacy site header block, I noticed two differences in the menu bar while the page is in mobile view.

1. The menu bar should be in accordion 
2. The News Bar font should be in bold

Please have a glimpse at the below snapshot.

![image](https://github.com/hlxsites/aldevron/assets/117751754/470a9253-0620-4d9a-810b-103d4563fc78)
![image](https://github.com/hlxsites/aldevron/assets/117751754/cf2a99f4-bf2e-4546-bdb1-10a538f428d4)

**Comment by teshukatepalli1** [comment]
Fixed please review

**Comment by Kummu007** [comment]
@teshukatepalli1  As discussed please look into this.

![image](https://github.com/hlxsites/aldevron/assets/117751754/72393323-dcc1-421b-93de-fde62c7f5062)

**Comment by pardeepgera23** [comment]
Hi Kumaresan - Please validate this again

**Comment by Kummu007** [comment]
This is is worked by the client, Hence we are considering only functional bugs.
