### ISSUE TITLE
Header--URL should open in new tab

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#22]
Hi Team,

While comparing the developed header block with the legacy site header block, the noticed difference is, that the provided URL should open in the new tab but the links are opening the same tab.

**Page path Details:-**
1. About us/Career
2. About us/ Code of Conduct and Ethics
3. About us/ Supplier Code of Conduct and Ethics

**Comment by teshukatepalli1** [comment]
Please add italic to make the link open in new tab for header block

**Comment by Kummu007** [comment]
Thanks for the update @teshukatepalli1, the provided URL is opening in the new tab but there is a change in the text format and the hover is not working.

![Header target blank](https://github.com/hlxsites/aldevron/assets/117751754/5846707c-ef88-4e17-a385-09e4108e775b)

**Comment by Kummu007** [comment]
This is working as expected.

Note:- If the URL needs to open in the new tab then we have to add a link and bold the text.
