### ISSUE TITLE
Sanity Check- Home Page

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#221]
Hi Team, 

I have noticed that a hero banner CTA is a bg color issue. Please look into the below snap and do the needful.

https://main--aldevron--hlxsites.hlx.page/

https://www.aldevron.com/

![image](https://github.com/hlxsites/aldevron/assets/117751754/860f3b6b-07fc-443e-aa5c-ff52196ad8d8)

![image](https://github.com/hlxsites/aldevron/assets/117751754/01cf50b4-f5e9-4da9-b6e7-92069203a8b1)

**Comment by pardeepgera23** [comment]
Fixed..Please validate

**Comment by Kummu007** [comment]
This is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/b6a5f734-b7e7-4404-919c-1353689f3c5c)
