### ISSUE TITLE
Sanity Check- /custom-manufacturing/rna

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#228]
Hi Team,

I have noticed a few observations which are given below. Please look into the below and do the needful.

Reference Links:-

**Main:-** https://main--aldevron--hlxsites.hlx.page/custom-manufacturing/rna
**Legacy:-** https://www.aldevron.com/platforms/mrna-production

**1. In Technical Expertise, the word in Vitro Italic is missing
2. The word Webinar Bold style is missing
3. Space issue between image and H1
4. In Facilities, the titles should be bold
5. In form,  Privacy Policy and Terms of Use URLs are leading to Aldevron.com**

**Detailed:-**
1. In Technical Expertise, the word **in Vitro** on the 4th bullet Italic style  is missing
![image](https://github.com/hlxsites/aldevron/assets/117751754/191e17a1-a98a-44c9-b40e-8584dcb2396c)

![image](https://github.com/hlxsites/aldevron/assets/117751754/72f00e38-e4fb-496c-b2ff-e9574b83c780)

2. The word **Webinar** Bold style is missing.

![image](https://github.com/hlxsites/aldevron/assets/117751754/c3f36f29-4b50-42ec-b542-cefa933f6a60)

![image](https://github.com/hlxsites/aldevron/assets/117751754/9b1a09c1-5f29-41f9-8837-213f8edfa10b)

3. Space issue between image and H1
![image](https://github.com/hlxsites/aldevron/assets/117751754/26f1151b-3bba-47fe-b101-ac2cde418d2f)

![image](https://github.com/hlxsites/aldevron/assets/117751754/69020000-ff8b-4ab8-b989-cca5a1107573)

4. In Facilities, the titles should be bold.

![image](https://github.com/hlxsites/aldevron/assets/117751754/7c7b2c79-afc9-45a0-bfed-27df318cdab6)

![image](https://github.com/hlxsites/aldevron/assets/117751754/d2ad2806-fc77-4d98-80bb-ef46433c1490)

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate

**Comment by Kummu007** [comment]
This is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/d8f6d000-0c43-4f19-bc02-890e56317f8c)

![image](https://github.com/hlxsites/aldevron/assets/117751754/61a2fa3d-8b16-4cde-b016-8aba9cea9eed)

![image](https://github.com/hlxsites/aldevron/assets/117751754/514a95b4-c7d0-4883-98ba-760c31517242)

![image](https://github.com/hlxsites/aldevron/assets/117751754/dda72943-ca19-4d65-9f9c-59ca2ce25a21)

![image](https://github.com/hlxsites/aldevron/assets/117751754/ecbad5bd-5ea0-4819-a8b6-53b7f4963dfc)
