### ISSUE TITLE
Sanity Check-custom-manufacturing/custom-protein-services

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#231]
Hi Team,

I have noticed a few observations which are given below. Please look into the below and do the needful.

Reference Links:-

**Main:-** https://main--aldevron--hlxsites.hlx.page/custom-manufacturing/custom-protein-services
**Legacy:-** https://www.aldevron.com/service/custom-protein-services

**1. Borders issue for the H1 text.
2. Bullet points padding issue
3. Text size issue
4. Form Image alignment issue.** 

Detailed:-

1. Borders issue for the H1 text, In the legacy there are no borders for the h1.

![image](https://github.com/hlxsites/aldevron/assets/117751754/ce9085d1-9084-4604-9608-559d9af2e494)

![image](https://github.com/hlxsites/aldevron/assets/117751754/799ae1ef-8eb6-4b46-8f4a-05770e458016)

2. Bullet points padding issue, padding is available in the legacy site but not in the Franklin

![image](https://github.com/hlxsites/aldevron/assets/117751754/186f145f-4148-4a6f-ae8c-d602ce39594a)

![image](https://github.com/hlxsites/aldevron/assets/117751754/f20079db-a37e-4b21-8f1f-bf4fd6515963)

3. Text size issue, Please look into the below snap.

![image](https://github.com/hlxsites/aldevron/assets/117751754/4d6461f8-e099-4002-923a-c7d53115c743)

![image](https://github.com/hlxsites/aldevron/assets/117751754/ba11d905-5f59-41a7-b41f-2c06c9c99893)

4. Form Image alignment issue, The image in the form is not aligned as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/c238f9c2-dea6-4a4e-9151-b363c4c6d8ff)

![image](https://github.com/hlxsites/aldevron/assets/117751754/4adede0b-86f0-428e-87bd-81e75e78eae0)

**Comment by pardeepgera23** [comment]
For point 1, vertical bars will be available for all headings upto H3 to make it consistent. This is agreed with client.
Point 3 is fixed.

Point 2 and 4 - callout made to client as technical limitation.

**Comment by Kummu007** [comment]
As per the above thread, This is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/e97b3931-1ea3-45f1-bde8-82178a1202f1)

![image](https://github.com/hlxsites/aldevron/assets/117751754/284f64f7-587b-49bb-b253-673a91ee0dd8)

![image](https://github.com/hlxsites/aldevron/assets/117751754/e9e5e5a4-37c1-4466-ae79-db4599969e0d)
