### ISSUE TITLE
Header- CTA should be Blank 

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#24]
Hi Team,

While comparing the developed header block with the legacy site header block, I noticed that for the below-given pages, the URL links should be blank which means the page CTA should be blank. Although I have tried to remove the link, there is a breach in the font face and font style (please refer to the image below).

**Page path Details:-**

1. Services
2. Products/Viral Vector
3. Products/Enzymes
4. Products/DNA/RNA Report

**SS with link:-**
![image](https://github.com/hlxsites/aldevron/assets/117751754/43f3d11d-acc9-4d2e-83c1-ec9838be1fec)

**SS after removing a link:-**
![image](https://github.com/hlxsites/aldevron/assets/117751754/07cacc72-98d0-4cd8-b12e-3810ff6bc8ec)

**Comment by teshukatepalli1** [comment]
Fixed this issue. Please verify and close

**Comment by Kummu007** [comment]
@teshukatepalli1 this is not working as expected

**Comment by pardeepgera23** [comment]
Hi Kumaresan - As per discussion with Client, we don't have any links in menu navigation which don't point to a page. And if needed in future, thy can redirect the user to home page by providing the link to home.
We can close this issue.

**Comment by Kummu007** [comment]
As per the above thread,  we don't have any links in menu navigation that don't point to a page. And if needed in the future, thy can redirect the user to the home page by providing the link to the home.

So, closing the ticket
