### ISSUE TITLE
Sanity Check- catalog-products/viral-vector-plasmids/pald-aav

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#242]
Hi Team,

I have noticed a few observations which are given below. Please look into the below and do the needful.

Reference Links:-

**Main:-** https://main--aldevron--hlxsites.hlx.page/catalog-products/viral-vector-plasmids/pald-aav
Reference: Refer the document.

**"1. Mobile view, Cart Table issue
2. Zoomed Image issue
3. Mobile view, Image overlap issue
4. Mobile View, Zoom image is not working"**

Detailed:-

1. Mobile view, Cart Table issue
![image](https://github.com/hlxsites/aldevron/assets/117751754/ae8f4f33-887e-4b7c-9803-9e6c0c8981e7)

![image](https://github.com/hlxsites/aldevron/assets/117751754/6e7b675e-cd8c-403b-a80d-3143cfed7a2a)

2.  Zoomed Image issue, Alignment and not able to zoom the image.
 
![image](https://github.com/hlxsites/aldevron/assets/117751754/e4b1667f-198d-4bfc-be82-6cb96177447f)

![image](https://github.com/hlxsites/aldevron/assets/117751754/772316d6-996b-416e-b0a0-76c0388177c3)

3. Mobile view, Image overlap issue
![image](https://github.com/hlxsites/aldevron/assets/117751754/b47cc5d5-733c-49a7-8045-cc73d0b55b2e)

4. Mobile View, Zoom image is not working

![image](https://github.com/hlxsites/aldevron/assets/117751754/ee46f40b-2b8f-42bb-bbad-8af3054b7975)

**Comment by Vinaykumargujja** [comment]
1. Provided image is not a correct size one. Please insert the images actual size in the authoring doc to get it zoomed in.
2. Overlapping issue is fixed.

**Comment by Kummu007** [comment]
Issues 1 and 2 are fixed
Issues 2 and 4 need to be re-validated, once an image of good resolution is authored.

**Comment by Kummu007** [comment]
This is working as expected, Hence closing the ticket.
