### ISSUE TITLE
Sanity Check- /resources/product-guides#platform-brochures

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#254]
Hi Team,

I have noticed a few observations which are given below. Please look into the below and do the needful.

Reference Links:-

Franklin site:- https://main--aldevron--hlxsites.hlx.page/resources/product-guides#platform-brochures
Existing site:- https://www.aldevron.com/resources/product-guides#productsandservices

1. The Hower effect is missing the text. Please look into the below snap and do the needful.

![image](https://github.com/hlxsites/aldevron/assets/117751754/1fb8799f-398c-422c-a330-0a5677c473fa)

![image](https://github.com/hlxsites/aldevron/assets/117751754/228ec086-3727-4374-885d-824e96845587)

**Comment by pardeepgera23** [comment]
Hi Kumaresan,

As discussed this is not an issue and designed for having consistent hover effect throughout website for all links.

**Comment by Kummu007** [comment]
As per the above thread, "designed for having consistent hover effect throughout the website for all links."

Hence closing the thread
