### ISSUE TITLE
Bug with Authoring the Author component

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/aldevron#275]
I’m working on posting a few blogs, but as one posted without issues, the other one I’m working on is giving an “out-of-standard” author box as it’s making links to buttons and adding a background to the author image. Can you please look at it and see how it can be fixed?
 
https://main--aldevron--hlxsites.hlx.page/drafts/focus-on-crispr-delivery-methods

![image](https://github.com/hlxsites/aldevron/assets/124819426/8ffced48-862b-49ee-bb44-a23d26bf3766)

vs

![image](https://github.com/hlxsites/aldevron/assets/124819426/be508f38-40ce-4bad-9038-ed25310fc59f)

**Comment by teshukatepalli1** [comment]
Hi @davenichols-DHLS , The issue is related to authering. There is a hidden space between image and link. We just need to remove that. Removed it. 

cc: @pardeepgera23 , @ramesh-gspann

**Comment by pardeepgera23** [comment]
Teshu and Ramesh have connected over call and Teshu has explained the correct way of authoring this block to Ramesh
