### ISSUE TITLE
Hero -Mobile view/Text Alignment Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#28]
Hi Team,

I have noticed that there is a text alignment issue when the hero banner is in the mobile view.

Please look at the below snapshots.

![image](https://github.com/hlxsites/aldevron/assets/117751754/467afbe5-8a8e-445c-98dc-cf2b935dc16d)

![image](https://github.com/hlxsites/aldevron/assets/117751754/c0989b67-0065-47c2-ae9c-6ca652d0a072)

**Comment by gowtamibetireddy** [comment]
Issue fixed & updated code merged to main branch

**Comment by Kummu007** [comment]
@teshukatepalli1 Please assign back once the PR is merge

**Comment by teshukatepalli1** [comment]
Hi @Kummu007  I have made the hero banner consistant. here it dont change any height and fixed to 310 px. Please make the content based on that 310px. Assigning for you to retest

**Comment by Kummu007** [comment]
@teshukatepalli1  as discussed, there is an issue with the h1 title color.

https://main--aldevron--hlxsites.hlx.page/qe-test/hero-test

https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid

![image](https://github.com/hlxsites/aldevron/assets/117751754/2988581c-6a9c-40b9-a05f-60102e1c34ea)

![image](https://github.com/hlxsites/aldevron/assets/117751754/6ea0b2d6-1a27-4910-91dd-552668baa128)

**Comment by Kummu007** [comment]
This is working as expected. Hence closing the ticket

![image](https://github.com/hlxsites/aldevron/assets/117751754/1a51bf5c-5750-44b3-906a-0b7cb08bf4e6)
