### ISSUE TITLE
Header- Lazy Loading

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#29]
Hi Team,

I have noticed that there is a delay in loading the header while refreshing the page.

**EDS Site:-**

![image](https://github.com/hlxsites/aldevron/assets/117751754/e4494f85-f7a7-4c84-83a9-d91d1bd19f0d)

**Comment by teshukatepalli1** [comment]
Hi @Kummu007  Based on confirmation with @dkuntze  Lazy loading is ok

**Comment by Kummu007** [comment]
Hi @teshukatepalli1 

Thanks for the update. As per the above the customer is okay with the header lazy loading. 

Hence closing the ticket.
