### ISSUE TITLE
Hero - CTA Tooltip Text Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#31]
Hi Team,

I have noticed that when the mouse moves over the CTA the tooltip text is appearing on the screen but not in the legacy site. So, expecting the same on the EDS site also.

![image](https://github.com/hlxsites/aldevron/assets/117751754/b4700d0e-07d4-4ee2-892d-a506be25a9e9)

![image](https://github.com/hlxsites/aldevron/assets/117751754/e6ef622f-1f96-48d9-865c-c24c81693a75)

**Comment by teshukatepalli1** [comment]
Hi @Kummu007  Look like it is fixed please look into it once

**Comment by Kummu007** [comment]
This is working as expected. Hence closing the ticket.
