### ISSUE TITLE
Hero - Registered trademark symbol ® superscript text Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#32]
Hi Team,

I have noticed that the sup tag is missing for the Registered trademark symbol in the hero banner. 

Please look into the below snap.

![image](https://github.com/hlxsites/aldevron/assets/117751754/a9c4d1fe-ba77-4449-90b8-25515ddb89b9)
![image](https://github.com/hlxsites/aldevron/assets/117751754/fd2bad8a-03bb-4cc1-b72f-d50c1fab1694)

**Comment by gowtamibetireddy** [comment]
Hi @Kummu007 the issue is fixed & the updated code will be on main once PR is merged. 
Note: Please apply superscript tag for trademark.
Let me know if any.
Thank you!

**Comment by Kummu007** [comment]
@teshukatepalli1  Please assign back once the PR is merge

**Comment by Kummu007** [comment]
@teshukatepalli1  thanks for the update. This is working as expected. Hence closing this ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/a9bd33af-6e89-470c-a00e-16debefb770b)
