### ISSUE TITLE
Image Block implementation

### ISSUE THREAD

**Issue by gowtamibetireddy** [hlxsites/aldevron#38]
Feature Requirement:
Imageshyperlink
User Story: This block will be used to author a single image with or without link.
ref link: https://www.aldevron.com/platforms/mrna-production
![image](https://github.com/hlxsites/aldevron/assets/147179869/c88e1fbe-6197-4926-815e-2bd780d52360)

Success Criteria:
The component should be display as expected in Aldevron site, in desktop, tablet and mobile views.

Authoring guide:
1. Insert a table with two rows. (full width)
2. In the first row, provide the name of the block as "Imageshyperlink"
3. Add the image in the second field. Link is an optional field and can be used based on the requirement.
![image](https://github.com/hlxsites/aldevron/assets/147179869/a3f21fa1-6a0b-437c-badf-86ab5af47e2c)

**Comment by gowtamibetireddy** [comment]
@Kummu007 Its ready for QA.
Sample test url: https://main--aldevron--hlxsites.hlx.page/test/imageshyperlink

**Comment by Kummu007** [comment]
Locked a Bug.

Image Hyperlink - Tooltip Text Issue #84
