### ISSUE TITLE
Footer-Social Media Icons Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#40]
Hi Team,

While comparing the developed Footer block with the legacy site Footer block, identified a couple of issues which are mentioned below.

**Issue-1:-**

While the size is reducing, there is an alignment issue in the social media icons section.

![Footer](https://github.com/hlxsites/aldevron/assets/117751754/61c29c29-6a4b-4782-9ed0-fcc63fd2b03e)
![Footer-Legacy](https://github.com/hlxsites/aldevron/assets/117751754/cc73689a-7a53-4387-93ae-68d19c180b18)

**Issue-2**

When the page is in mobile view the icons should get shuffled like the legacy site but it's not happening in the EDS.

![Footer social icon](https://github.com/hlxsites/aldevron/assets/117751754/a8b16a91-0591-4592-9556-ae02664f4c8a)
![Footer social icon-Legacy](https://github.com/hlxsites/aldevron/assets/117751754/0f9f15b2-974a-4866-adb1-0dce2b6b257f)

**Comment by Vinaykumargujja** [comment]
Hi Kumaresan,
They are used earlier in the existing site float, this is the issue with the existing issue. We cleared it with Flex display property. So This is not an issue. @umamenda , @teshukatepalli1 , @Kummu007 , @pardeepgera23

**Comment by Kummu007** [comment]
Thaks for the update @Vinaykumargujja 

As mentioned in the above thread, this is not an issue. Hence closing the ticket.
