### ISSUE TITLE
Create Cards/showcards block

### ISSUE THREAD

**Issue by gowtamibetireddy** [hlxsites/aldevron#41]
Feature Requirement:
Show Cards
User Story:
This block is used to author the Image, title, description & the button field. It will be shown as below.
Platforms:
![image](https://github.com/hlxsites/aldevron/assets/147179869/fac50074-d277-4ffe-a765-c11ebd061d05)
Services:
![image](https://github.com/hlxsites/aldevron/assets/147179869/1c00b26f-1fd6-403e-ac26-e29285cfa72e)

### Authoring steps for platform section in Home page:
1. Insert a table with the required number of rows depending on how many cards are having on the page (for ex: 3) and a single column.
2. In the first row, provide the name of the block "showcards (data-block-heading--Platforms)". Here, "Platforms" is the name of heading for that section. You can replace it with any text it will be updated accordingly and If you don't need any heading at all you can remove the text as well after showcards {ie., (data-block-heading--Platforms)} and provide only "showcards".
3. In the next row, provide the image, heading, description and button data respectively one beneath the other.
4. Repeat step 3 by providing each card information {ie., Image, heading, description and button} in each row, until you complete all the cards on the page.
5. Please find the attached screenshot for your reference.
![image](https://github.com/hlxsites/aldevron/assets/145748430/6d71bcbc-5571-4806-af42-4ad5e4bd85e9)

### Authoring steps for Services section in Home page:
1. Insert a table with the required number of rows depending on how many cards are having on the page (for ex: 3) and 2 columns.
2. Merge the two columns in the first row, then provide the name of block "showcards (data-block-heading--Services)". Here, "Services" is the name of heading for that section. You can replace it with any text it will be updated accordingly and If you don't need any heading at all you can remove the text as well after showcards {ie., (data-block-heading--Services)} and provide only "showcards".
3. In the next row first column, provide the image and in the second column provide heading, description and button data respectively one beneath the other.
4. Repeat step 3 by providing each card Image in the first column and related information {ie., heading, description and button} in second column, until you complete all the cards on the page.
5. Please find the attached screenshot for your reference.
![image](https://github.com/hlxsites/aldevron/assets/145748430/4988d88a-810d-492e-94ca-e4f9d8dad3b9)

**Comment by gowtamibetireddy** [comment]
@Kummu007 its ready for QA

**Comment by Kummu007** [comment]
Hi Team, 

as per the update, that this block is no longer needed
