### ISSUE TITLE
Create table block with multiple variations

### ISSUE THREAD

**Issue by teshukatepalli1** [hlxsites/aldevron#45]
**Authoring steps for Table block:-**
1. Create a table with 2 rows then provide the name of the block in 1st row as "Table(heading-top, heading-left,outer)".
![image](https://github.com/hlxsites/aldevron/assets/147372269/a315ff65-f295-4906-a15f-9c403d440e6f)

2. Insert new table in 2nd row with required number of rows and 5 columns.
![image](https://github.com/hlxsites/aldevron/assets/147372269/a804691f-1554-400a-9f12-9d90974bbba1)

3. Merge 1st row's 2nd, 3rd, 4th and 5th columns and add the text.
![image](https://github.com/hlxsites/aldevron/assets/147372269/a90df6a2-0282-4259-8e20-0819ef33286a)

4. Then on the new table's 2nd row (created in step 3), merge column 2nd and 3rd. Rest shoud remain as it is.
![image](https://github.com/hlxsites/aldevron/assets/147372269/e0baca19-e582-46aa-9276-1dfa28ab5c8e)

5. Insert a table with 2 row's and 2 column's under the merged column( merged in step 4)
![image](https://github.com/hlxsites/aldevron/assets/147372269/e6d94808-d5ac-4092-b685-af92106cb76f)

6. Merged the 1st row's column created in step 5.
![image](https://github.com/hlxsites/aldevron/assets/147372269/99fc037d-0b80-4765-9f7c-e3de6db0b465)

7. Add data on the row's and column's as per requirement.
![image](https://github.com/hlxsites/aldevron/assets/147372269/453dcaed-8f81-48e4-b7e5-449937a529ef)

**Authoring steps for Table block with variation:-**
1. Create a table with 2 rows and Provide the name of the block in 1st row as "Table(heading-top,outer)".
2. Insert new table in 2nd row with required number of rows and 4 columns.
3. Add data on the row's and column's as per requirement.
![image](https://github.com/hlxsites/aldevron/assets/147372269/4ab692c3-63c7-4f1f-bfec-d069d7c6d42c)

**Authoring steps for Table block with variation:-**
1. Create a table with 2 rows and Provide the name of the block in 1st row as "Table(heading-left,outer,table-plain)".
2. Insert new table in 2nd row with required number of rows and 2 columns.
3. Add data on the row's and column's as per requirement.
![image](https://github.com/hlxsites/aldevron/assets/147372269/26e2600c-24dd-4716-80a9-5e278a6c6b2b)

@Kummu007 It's ready for QA.

**Comment by HimanshuChauhan06** [comment]
**Authoring steps for Table block:-**
1. Create a table with 2 rows then provide the name of the block in 1st row as "Table(heading-top, heading-left,outer)".
![image](https://github.com/hlxsites/aldevron/assets/147372269/a315ff65-f295-4906-a15f-9c403d440e6f)

2. Insert new table in 2nd row with required number of rows and 5 columns.
![image](https://github.com/hlxsites/aldevron/assets/147372269/a804691f-1554-400a-9f12-9d90974bbba1)

3. Merge 1st row's 2nd, 3rd, 4th and 5th columns and add the text.
![image](https://github.com/hlxsites/aldevron/assets/147372269/a90df6a2-0282-4259-8e20-0819ef33286a)

4. Then on the new table's 2nd row (created in step 3), merge column 2nd and 3rd. Rest shoud remain as it is.
![image](https://github.com/hlxsites/aldevron/assets/147372269/e0baca19-e582-46aa-9276-1dfa28ab5c8e)

5. Insert a table with 2 row's and 2 column's under the merged column( merged in step 4)
![image](https://github.com/hlxsites/aldevron/assets/147372269/e6d94808-d5ac-4092-b685-af92106cb76f)

6. Merged the 1st row's column created in step 5.
![image](https://github.com/hlxsites/aldevron/assets/147372269/99fc037d-0b80-4765-9f7c-e3de6db0b465)

7. Add data on the row's and column's as per requirement.
![image](https://github.com/hlxsites/aldevron/assets/147372269/453dcaed-8f81-48e4-b7e5-449937a529ef)


**Authoring steps for Table block with variation:-**
1. Create a table with 2 rows and Provide the name of the block in 1st row as "Table(heading-top,outer)".
2. Insert new table in 2nd row with required number of rows and 4 columns.
3. Add data on the row's and column's as per requirement.
![image](https://github.com/hlxsites/aldevron/assets/147372269/4ab692c3-63c7-4f1f-bfec-d069d7c6d42c)

**Authoring steps for Table block with variation:-**
1. Create a table with 2 rows and Provide the name of the block in 1st row as "Table(heading-left,outer,table-plain)".
2. Insert new table in 2nd row with required number of rows and 2 columns.
3. Add data on the row's and column's as per requirement.
![image](https://github.com/hlxsites/aldevron/assets/147372269/26e2600c-24dd-4716-80a9-5e278a6c6b2b)

**Comment by Kummu007** [comment]
Table(heading-top, heading-left,outer) #194

**Comment by Kummu007** [comment]
This is working as expected.
