### ISSUE TITLE
Create tabs block

### ISSUE THREAD

**Issue by teshukatepalli1** [hlxsites/aldevron#46]
**Authoring steps for Tabs block:**
1. Insert a Table with required number of rows and 2 columns.
2. In the first row, merge the two columns and then provide the name of the block as "Tabs".
3. In the next row first column, Provide the details as "Tab 1" and in the second column, Provide the corresponding content (ie., only text) which is present under tab 1.
4. In the next row first column, Provide the details as "Tab 2" and in the second column, Provide the corresponding content (ie., only text) which is present under tab 2 and so on...
4. Repeat the above step until you complete all the number of Tabs.
Please find the below screenshot for your reference.
![image](https://github.com/hlxsites/aldevron/assets/145748430/bc0af635-fb7f-4829-abb7-53bae6176905)
**Preview Image:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/40eb44af-da6c-451f-aba4-2f7ff15771de)

**Authoring steps for Tabs with Table Variation:**
1. Insert a Table with required number of rows and 2 columns.
2. In the first row, merge the two columns and then provide the name of the block as "Tabs(tabs-with-table)".
3. In the next row first column, Provide the details as "Tab 1" and in the second column, Provide the corresponding content (ie., text and Table or only Table)  which is present under tab 1. 
	a. If any text is present above the Table then insert a table with required number of rows and columns under the text In the second row second column. Otherwise, you can simply insert a table with required number of rows and columns.
	b. Please author the table content as is without giving any specific name for it in the first row.
 
4. In the next row first column, Provide the details as "Tab 2" and in the second column, Provide the corresponding content (ie., text and Table or only Table) which is present under tab 2 and so on...
4. Repeat the step 3 until you complete all the number of Tabs.
Please find the below screenshot for your reference.
![image](https://github.com/hlxsites/aldevron/assets/145748430/0c7c42cf-5140-41c6-830f-7c6e856019ed)
**Preview Images:**
![image](https://github.com/hlxsites/aldevron/assets/145748430/cc2d68cf-bbeb-47c8-becd-1e3940fd1680)
![image](https://github.com/hlxsites/aldevron/assets/145748430/26572bbf-e336-495e-8b47-6416a3a6ff38)

**Comment by gowtamibetireddy** [comment]
@Kummu007  its ready for QA

**Comment by Kummu007** [comment]
Tabs - CTA/New Tab #131	Open
Tabs - Background Color #132	Closed
Tabs - List order Issue #133	Closed
Tabs - Alignment Issue #134	Closed

**Comment by Kummu007** [comment]
This is working as expected.
