### ISSUE TITLE
Accordion - Caret(downward-facing arrow) Alignment issue 

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#47]
Hi Team, 

I have noticed an issue in the accordion Caret(downward-facing arrow) Alignment if the cell is empty in the edit mode. 

Please look into the below snap and do the needful.

![Accordion](https://github.com/hlxsites/aldevron/assets/117751754/1294117c-763e-44fa-83b3-2195e2f8fa02)

![Accordion-Preview](https://github.com/hlxsites/aldevron/assets/117751754/864b0bf2-8bff-442b-91e2-93df1a1068de)

**Comment by gowtamibetireddy** [comment]
Hi @Kummu007 issue got fixed & will be merged to main.

Thanks!

**Comment by Kummu007** [comment]
Hi @gowtamibetireddy, seems like the issue is not resolved yet.

Please check the below snap.

![image](https://github.com/hlxsites/aldevron/assets/117751754/611fca11-7400-4cc7-86ec-7542830e5c95)
![image](https://github.com/hlxsites/aldevron/assets/117751754/e344e843-b487-4c79-8c72-9220a5387e75)

**Comment by Kummu007** [comment]
This is working as expected. Hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/99ed0a8e-dc94-48b0-817b-11fe159f9804)

![image](https://github.com/hlxsites/aldevron/assets/117751754/8b8dce89-4a25-443e-a64c-69042003b0a9)
