### ISSUE TITLE
Create embed block for video display

### ISSUE THREAD

**Issue by pardeepgera23** [hlxsites/aldevron#5]

**Comment by gowtamibetireddy** [comment]
@Kummu007 its ready for QA.

**Comment by Kummu007** [comment]
A few Bugs have been locked which were related to this block.

Video Embed (YouTube)- Label and Icons are missing #66
Video Embed (YouTube)-Alignment issue #67
Video Embed (YouTube)- Tooltip text and Play button color missing #68

**Comment by Kummu007** [comment]
This is working as expected.
