### ISSUE TITLE
Create Hero Banner block

### ISSUE THREAD

**Issue by gowtamibetireddy** [hlxsites/aldevron#58]
**Feature Requirement**:  
Hero Banner
**User Story**: 
We need this Hero banner block to use where ever, we need an image as background and half of the the right side of the block should contain an another background image with one heading, some description and one button.

Existing component example is in main page of the Aldevron site, above the contact-us section component.

Please find the reference : https://www.aldevron.com/
![image](https://github.com/hlxsites/aldevron/assets/148342791/6e1ab30e-6b05-4db5-81e6-18f20d055276)

Success Criteria:
The component should be display as expected in Aldevron site, in desktop, tablet and mobile views.

 **Authoring guide** 
1. Insert a table with two rows. (first row - full width, second row 2 x 1)
2. In the first row, provide the name of the block along with the class name in brackets "Herobanner (right-content) ".
3. In the second row - provide the BG image in the first column and provide title, description and button in the second column as shown below.
![image](https://github.com/hlxsites/aldevron/assets/147179869/78596d90-84ad-44b3-b876-cc0f6442c0f7)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate this

**Comment by gowtamibetireddy** [comment]
@Kummu007 PFB urls
https://main--aldevron--hlxsites.hlx.page/test/sample-page
https://feature-herobanner--aldevron--hlxsites.hlx.page/test/sample-page

**Comment by Kummu007** [comment]
@gowtamibetireddy Can we have the block name i.e., which needs to be mentioned, while authoring the page.

**Comment by Kummu007** [comment]
This is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/f4969cce-cb88-4e5d-840c-998ad0964359)
