### ISSUE TITLE
Create accordion variation with CTA for expand all/collapse all

### ISSUE THREAD

**Issue by pardeepgera23** [hlxsites/aldevron#63]
Use case: Create a variation of existing Accordion block which will show hide a CTA to expand collapse all rows.
Refer to example here - https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid/faq

Feature Requirement:
Accordion
User Story:
This Accordion will expand and collapse based on 'CTA' and space between the accordions will be based on 'spacer'.
Platforms:
![Pasted Graphic](https://github.com/hlxsites/aldevron/assets/148449677/0e603ef1-5fc3-4e20-9ce6-6a54ae502da5)

![Pasted Graphic 1](https://github.com/hlxsites/aldevron/assets/148449677/1d85ea89-fcec-4d79-9e40-8009cbe95d6a)

**Authoring steps :**

1- Insert a table with 2 columns and required rows (as per the number of queries).
2-In the first row provide the name of the block as "Accordion(CTA)". If you don't append CTA in the block name then **Collapse All/Expand All** button will not be visible as per the functionality.
3-If we need space between the accordions , we have to append "spacer" in the block name as well i.e "Accordion(CTA, spacer)". 
4-Place the question in the next rows of first column and answers in the second column. Find the below screenshot for your reference.
![Pasted Graphic 2](https://github.com/hlxsites/aldevron/assets/148449677/c6c5fb8d-a219-412c-bd56-c305351fd21c)
![image](https://github.com/hlxsites/aldevron/assets/148449677/9ec0e596-76d1-4463-b61d-66af0157ff9e)

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate

**Comment by Kummu007** [comment]
@ssahoo1996  thanks for the update, this is working as expected.

https://main--aldevron--hlxsites.hlx.page/qe-test/accordion-with-collapse-all#
