### ISSUE TITLE
Video Embed (YouTube)- Label and Icons are missing

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#66]
Hi Team, 

I have noticed that the Watch Later and Share icons are missing and the Watch on youtube label is missing. Please look in to the below snap and do the needful.

**Legacy site:-**

![Video-Legacy](https://github.com/hlxsites/aldevron/assets/117751754/2b8893c3-56d2-4c02-94f0-c0b4ad80b74c)

**EDS:-**

![Video-EDS](https://github.com/hlxsites/aldevron/assets/117751754/5c431b9c-47df-4c74-951e-ca5057472817)

**Comment by pardeepgera23** [comment]
@Kummu007 - As confirmed with client yesterday, we can ignore this issue as this is due to lite-video-embed script for performance gain.

**Comment by Kummu007** [comment]
As mentioned in the above thread,  we can ignore this issue as this is due to the lite-video-embed script for performance gain.

Hence closing the ticket.
