### ISSUE TITLE
Video Embed (YouTube)-Alignment issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#67]
Hi Team,

I have noticed that there is an issue in the alignment. In the legacy, the YouTube video is aligned in the center but in EDS it is aligned to the left.

**EDS:-**
![Video-EDS alignment](https://github.com/hlxsites/aldevron/assets/117751754/c14445d7-a207-4914-8c96-17ac4ea26d08)

**LEGACY:-**

![Video-Legacy alignment](https://github.com/hlxsites/aldevron/assets/117751754/ae4ff7e3-37bf-451a-b3b0-f25cc1c76754)

**Comment by teshukatepalli1** [comment]
Hi @Kummu007 . Please try to apply the default template in metadata and check whether it is working or not. Assigning you for this observation.

**Comment by Kummu007** [comment]
@teshukatepalli1  thanks for the update and this is working as expected.

![image](https://github.com/hlxsites/aldevron/assets/117751754/ef57a545-6001-4d9f-918f-7e7bd0c36aca)
