### ISSUE TITLE
Video Embed (YouTube)- Tooltip text and Play button color missing

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#68]
Hi Team, 

I have noticed that the play tooltip text and play button color are missing. Please look into the below snap.

**Legacy play button:-**

![Video-legacy button color](https://github.com/hlxsites/aldevron/assets/117751754/c6ba455b-f958-47ea-b110-34bb0292c7c1)

**EDS play button:-**

![Video-EDS button color](https://github.com/hlxsites/aldevron/assets/117751754/3a95f5b3-5fc1-4e44-876e-2847a4b61c54)

**EDS play tooltip text:-**

![Video-EDS tooltip text](https://github.com/hlxsites/aldevron/assets/117751754/76a0c8b3-6304-474a-8157-27bdced334eb)

**Legacy play tooltip text:-**

![Video-legacy tooltip text](https://github.com/hlxsites/aldevron/assets/117751754/87a36b96-38d1-45df-9c2b-bf8aa76ed298)

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate.

**Comment by Kummu007** [comment]
This is working as expected, Hence closing the ticket.
