### ISSUE TITLE
Video Embed (YouTube)- Pause overlay issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#69]
Hi Team, 

I have noticed that there is a pause overlay popup appearing on the EDS site when the video is paused. Please look into the below snap.

![Video-EDS overlay](https://github.com/hlxsites/aldevron/assets/117751754/539949d3-e91e-4ac7-9770-9d9797eda546)
![Video-Legacy overlay](https://github.com/hlxsites/aldevron/assets/117751754/1691e1f7-e274-4de2-83fe-08d53022dedf)

**Comment by pardeepgera23** [comment]
Hi Kumaresan - The same behaviour is on existing website also. Please re-validate and let us know.

**Comment by Kummu007** [comment]
Hi Team, 

This is working as expected, hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/45ce0ed8-a838-4212-90e7-33e23ff49037)
