### ISSUE TITLE
Footer-Mobile View- Footnote padding issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#72]
Hi Team,

While comparing the developed Footer block with the legacy site Footer block, in mobile view for the legacy footer footnote padding is 10px but in the EDS it is 20px.

Please look into the below snap and do the needful.

![Footnote padding-EDS](https://github.com/hlxsites/aldevron/assets/117751754/6a579f6b-e4ea-4d09-94f4-6a284dcaa1c7)
![Footnote padding-legacy](https://github.com/hlxsites/aldevron/assets/117751754/201432f4-212c-44c6-bb06-384334977495)
vi

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
The issue is resolved hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/7785cbc6-f7cc-472e-919a-1df7d11c8986)
