### ISSUE TITLE
Contact Us- punctuation mark (') issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#74]
Hi Team, 

I have noticed that the punctuation mark (') is appearing on the site page which is built with EDS. Please look into the below snap.

![image](https://github.com/hlxsites/aldevron/assets/117751754/81db2f30-ce71-4cfe-a3ea-4b1e48eb2aaf)
![Contactus-EDS](https://github.com/hlxsites/aldevron/assets/117751754/5a511f91-735a-4f86-9435-2c7f66fe9b06)

**Comment by gowtamibetireddy** [comment]
Hi @Kummu007 
fixed the below issues
1. punctuation mark (')
2. button border
3. removed on hover title.
You can verify the latest changes here
https://feature-contactus-issue-74--aldevron--hlxsites.hlx.page/qe-test/contact-us

**Comment by Kummu007** [comment]
@gowtamibetireddy  thanks for the update, the issue is not resolved in the href. Please check the below snapshot.

![Uploading Contactus (') issue-EDS.png…]()

**Comment by gowtamibetireddy** [comment]
@Kummu007 I don't see any issue there. Please reverify once. Thanks!
![image](https://github.com/hlxsites/aldevron/assets/147179869/c63598ff-dbb4-453c-bbe2-5341eb2dbb3f)
https://main--aldevron--hlxsites.hlx.page/qe-test/contact-us

**Comment by gowtamibetireddy** [comment]
https://main--aldevron--hlxsites.hlx.page/qe-test/contact-us
https://feature-contactus-issue-74--aldevron--hlxsites.hlx.page/test/contactus

**Comment by gowtamibetireddy** [comment]
@Kummu007 all issues has been fixed and its ready for QA.

**Comment by Kummu007** [comment]
@gowtamibetireddy thanks for the update, This is working as expected. Hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/f1447f60-1798-499c-b3ab-5798aff24640)
