### ISSUE TITLE
Hero Banner- Tittle and CTA Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#80]
Hi Team,

I have noticed an issue with the hero banner, title, and CTA are behaving by themselves. Please look into the below snap.

![image](https://github.com/hlxsites/aldevron/assets/117751754/b770ca40-a05e-4b79-b49c-1b3015c9ab9e)
![image](https://github.com/hlxsites/aldevron/assets/117751754/7906284c-19e1-4f18-8476-66e9339e823d)

@Vinaykumargujja as discussed, please look into this.

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
@Vinaykumargujja  this is working as expected, can you work on the **tooltip text**? Please look into the below snap.

![image](https://github.com/hlxsites/aldevron/assets/117751754/a661adb8-657e-4e73-9e5f-d55fa484b618)

![image](https://github.com/hlxsites/aldevron/assets/117751754/58f9a647-b9fd-46bb-be1a-c56d43a14dd0)

**Comment by Vinaykumargujja** [comment]
Hi @Kummu007 ,
I pushed the code from another branch for the issue,
PR is just merged 15 hours back.
can you please test the page again with above mentioned link.

PR: https://github.com/hlxsites/aldevron/pull/126
https://github.com/hlxsites/aldevron/commit/95e444ca6dfd76be183614f8eb0f3688208a6e52

**link:** https://bug-hero-banner-cta-tooltip--aldevron--hlxsites.hlx.page/test/sample-page
 https://main--aldevron--hlxsites.hlx.page/test/sample-page
this is the link, You can test for the result.

**Comment by Kummu007** [comment]
@Vinaykumargujja  Thanks for the update, this is working as expected 

![image](https://github.com/hlxsites/aldevron/assets/117751754/f5c25709-dcf5-499d-983f-1d6715e80692)
