### ISSUE TITLE
Image Hyperlink - Tooltip Text Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#84]
Hi Team,

I have noticed that when the mouse moves over the CTA the tooltip text appears on the screen. Please look into the below snap and do the needful.

![image](https://github.com/hlxsites/aldevron/assets/117751754/a0004506-a247-4d00-ab70-49faa5119675)
![image](https://github.com/hlxsites/aldevron/assets/117751754/2704bd00-a8da-4f60-bf6e-a82c14280ab6)

**Comment by pardeepgera23** [comment]
@Kummu007  - Please validate

**Comment by Kummu007** [comment]
Hi @Vinaykumargujja, Thanks for the update, this issue is working as expected. Hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/c751343d-3ba3-4c69-a2df-3840724c8e1f)
