### ISSUE TITLE
Create block for Video Banner

### ISSUE THREAD

**Issue by pardeepgera23** [hlxsites/aldevron#91]
**Summary**

Create a block for video banner as per below link:
https://www.aldevron.com/25th-anniversary

**Comment by pardeepgera23** [comment]
**Authoring details:**

![image](https://github.com/hlxsites/aldevron/assets/147177349/ff92e434-899f-43cb-b58c-cd7bf1d128da)

![image](https://github.com/hlxsites/aldevron/assets/147177349/d08faab8-965a-4ec2-a917-7adaaecb3fe6)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
Add a bug.

Video Banner- Mobile View Background video issue #157

**Comment by Kummu007** [comment]
This is working as expected.
