### ISSUE TITLE
Accordion variation with CTA- Margin Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#92]
Hi Team, 

I have noticed an issue in the accordion variation with CTA, there is a margin issue. Please look into the below snap and do the needful.

![Accordion variation with CTA- Margin Issue-Legacy](https://github.com/hlxsites/aldevron/assets/117751754/86733bdb-ee03-43e9-964f-2400f8a57acb)
![Accordion variation with CTA- Margin Issue-EDS](https://github.com/hlxsites/aldevron/assets/117751754/e2b42bbf-18b1-4ce2-b9d6-5e5e785d7e99)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate.

**Comment by Kummu007** [comment]
Working On it!!

**Comment by Kummu007** [comment]
Hi @ssahoo1996 

Thanks for the update, the issue is almost corrected but can you just make a padding correction between the expand all radio button and the accordion. Please look into the below snap.

![image](https://github.com/hlxsites/aldevron/assets/117751754/16302df0-2b34-4243-9e47-4a322ecdd01f)

![image](https://github.com/hlxsites/aldevron/assets/117751754/64b7242e-f18c-4cea-9ce8-f2c4548af3ef)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate and close.

**Comment by Kummu007** [comment]
@ssahoo1996, this issue still persists and **Exapand all** radio button is missing. Please look into the below snap.

@pardeepgera23 FYI

![Accordion variation with CTA- Margin Issue-EDS-2](https://github.com/hlxsites/aldevron/assets/117751754/5a4990cf-f5e7-40f9-a130-c6fa1d9a8e22)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by Kummu007** [comment]
Hi Team, 

This is working as expected, hence closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/0d016667-99e0-40f4-8193-224307599301)
