### ISSUE TITLE
Accordion variation with CTA- Transition Effect Issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#95]
Hi Team, 

I have noticed that the animation effect is missing in the Accordion variation with CTA, Please compare the site with Legacy. 

Note:- Need more clarity please ping me.

https://main--aldevron--hlxsites.hlx.page/qe-test/accordion-with-collapse-all

https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid/faq

**Comment by Kummu007** [comment]
@ssahoo1996 can you check this

**Comment by ssahoo1996** [comment]
I've fixed the empty row issue in accordion, transition effect and padding issue. Please do check.

**Comment by Kummu007** [comment]
@ssahoo1996 as discussed, please check the below snap and do the needful.

Tooltip Issue.


https://main--aldevron--hlxsites.hlx.page/qe-test/accordion-with-collapse-all#
https://www.aldevron.com/our-services/plasmid-dna-production/nanoplasmid/faq

![image](https://github.com/hlxsites/aldevron/assets/117751754/8ef36bf1-056e-4af7-86b6-c13c6e65c431)

**Comment by pardeepgera23** [comment]
@Kummu007 - Please validate

**Comment by ssahoo1996** [comment]
I've fixed the transition effect issue. @Kummu007 please validate.

**Comment by Kummu007** [comment]
@ssahoo1996  Thanks for the update, this is working as expected.

https://main--aldevron--hlxsites.hlx.page/qe-test/accordion-with-collapse-all#
